# Generated by Django 5.0.4 on 2024-08-16 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_userapplication_unique_together_userpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="application_categories",
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="operating_system",
            field=models.CharField(
                blank=True,
                choices=[("mac", "Mac"), ("windows", "Windows"), ("linux", "Linux")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="key",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="value",
        ),
    ]
