# Generated by Django 5.0.4 on 2024-10-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_userpreference_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="application_categories",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
