# Generated by Django 5.0.4 on 2024-10-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_userpreference_application_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcut",
            name="submodule",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="linux",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="mac",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="windows",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
