# Generated by Django 5.0.4 on 2024-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_shortcut_submodule_alter_shortcut_linux_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcut",
            name="context",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
    ]
