# Generated by Django 5.0.4 on 2024-10-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_shortcut_context"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shortcut",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="idea",
            name="description",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="application_command",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="context",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="description",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="linux",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="mac",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="submodule",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="windows",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="operating_system",
            field=models.CharField(
                blank=True,
                choices=[("mac", "Mac"), ("windows", "Windows"), ("linux", "Linux")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usershortcut",
            name="user_linux",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usershortcut",
            name="user_mac",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usershortcut",
            name="user_windows",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="shortcut",
            unique_together={("application", "submodule", "command")},
        ),
    ]
