# Generated by Django 5.0.4 on 2024-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_shortcut_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shortcut",
            unique_together={("application", "submodule", "command")},
        ),
        migrations.AddField(
            model_name="shortcut",
            name="command_id",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="level",
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="shortcut",
            unique_together={
                ("application", "submodule", "command"),
                ("application", "submodule", "command_id"),
            },
        ),
    ]
