# Generated by Django 5.0.4 on 2024-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_shortcut_unique_together_shortcut_command_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcut",
            name="command_id",
            field=models.CharField(db_index=True, default="", max_length=200),
            preserve_default=False,
        ),
    ]
