name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mpa:main ./server

      - name: Login to Docker Hub
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $username -p $password

      - name: Push backend image
        env:
          username: ${{secrets.DOCKER_USERNAME}}
        run: docker push $username/mpa:main

      - name: Logout of Docker Hub
        run: docker logout
