name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mpa/web:main ./server

      - name: Login to Docker Hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $username -p $password

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mpa/web:main

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mpa/frontend:main

      - name: Logout of Docker Hub
        run: docker logout
